---
  language: ruby
  sudo: false
  rvm:
    - 2.1.2
  install:
    - bundle install --quiet
  script:
    - cd ruby
    - rubocop -fs -D
    - rake test

addons:
  code_climate:
    repo_token: 92dc5a2cd2a2ecb507ea7aa5bad6dd602dce8ec07c3e58bf595462819bfb7c21
